language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - pytest test_end_to_end.py


notifications:
  email:
    recipients:
      - rohan.padmanabhan15@imperial.ac.uk
    on_success: never
    on_failure: always

